navigation_standalone_index:
  path: /navigation
  controller: App\Navigating\Service\Http\Navigation\NavigationHttpService::index

navigation_standalone_preview:
  path: /navigation/preview
  controller: App\Navigating\Service\Http\Navigation\NavigationHttpService::preview
