navigation_standalone_index:
  path: /navigation
  controller: App\Navigating\Controller\NavigationController::index

navigation_standalone_preview:
  path: /navigation/preview
  controller: App\Navigating\Controller\NavigationController::preview
