parameters:
  app.default_database_url: 'sqlite:///%kernel.project_dir%/var/navigation.sqlite'

doctrine:
  dbal:
    url: '%env(default:app.default_database_url:DATABASE_URL)%'
  orm:
    auto_mapping: false
    mappings:
      Navigating:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Navigating\Entity'
        alias: Navigating
